version: "3.9"

services:
  app:
    build: .
    container_name: otk-server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /root/OTKServer/src/main/resources/static/images:/app/images:ro